apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data
  namespace: neon-test
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    consul.hashicorp.com/service-sync: 'true'
    consul.hashicorp.com/service-name: 'cassandra'
  name: cassandra
  namespace: neon-test
  labels:
    app: cassandra
spec:
  ports:
  - port: 9160
    name: thrift
    targetPort: 9160
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  namespace: neon-test
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.11.1
        ports:
        - containerPort: 9160
          name: thrift
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "MyCluster"
        - name: CASSANDRA_DC
          value: "dc1"
        - name: CASSANDRA_RACK
          value: "rack1"
        - name: CASSANDRA_START_RPC
          value: "true"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
      volumes:
      - name: cassandra-data
        persistentVolumeClaim:
          claimName: cassandra-data
