{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-nginx
  labels:
    {{- include "cong-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: 8181
      targetPort: 8181
      name: http
    - port: 8443
      targetPort: 8443
      name: https
  selector:
    {{- include "cong-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-nginx
  labels:
    {{- include "cong-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "cong-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "cong-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      serviceAccountName: {{ include "cong-chart.serviceAccountName" . }}
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          {{- with .Values.nginx.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8181
            - containerPort: 8443
          env:
            - name: PROXY_PORT
              value: "8181"
            - name: CONSUL_HOST
              value: "{{ include "cong-chart.fullname" . }}-consul"
          volumeMounts:
            - name: nginx-config-template
              mountPath: /etc/consul-templates/nginx.conf.ctmpl
              subPath: nginx.conf.ctmpl
            - name: nginx-certs
              mountPath: /self-ssl
      volumes:
        - name: nginx-config-template
          configMap:
            name: {{ include "cong-chart.fullname" . }}-nginx-config-template
        - name: nginx-certs
          secret:
            secretName: {{ include "cong-chart.fullname" . }}-nginx-certs
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-nginx-config-template
data:
  nginx.conf.ctmpl: |
    {{- .Values.nginx.configTemplate | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-nginx-certs
type: kubernetes.io/tls
data:
  {{- if and .Values.nginx.tls.crt .Values.nginx.tls.key }}
  tls.crt: {{ .Values.nginx.tls.crt | b64enc }}
  tls.key: {{ .Values.nginx.tls.key | b64enc }}
  {{- else }}
  {{- include "cong-chart.gen-certs" . | nindent 2 }}
  {{- end }}
{{- end }}