{{- if .Values.saq.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-saq
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "cong-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: saq
spec:
  ports:
    - port: 32123
      targetPort: 32123
  selector:
    {{- include "cong-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: saq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-saq
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "cong-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: saq
spec:
  replicas: {{ .Values.saq.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "cong-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: saq
  template:
    metadata:
      labels:
        {{- include "cong-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: saq
    spec:
      serviceAccountName: {{ include "cong-chart.serviceAccountName" . }}
      containers:
        - name: saq
          image: "{{ .Values.saq.image.repository }}:{{ .Values.saq.image.tag }}"
          imagePullPolicy: {{ .Values.saq.image.pullPolicy }}
          {{- with .Values.saq.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["/saq_run.sh"]
          args: ["start","--config","/saq.cfg","--logLevel","DEBUG","--basePath","/SAQ"]
          ports:
            - containerPort: 32123
          env:
            - name: CONSUL_HOST
              value: "{{ include "cong-chart.fullname" . }}-consul"
            - name: SAQ_ADVERTISE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: saq-data
              mountPath: /SAQ
            - name: maana-share
              mountPath: /maana_share
      volumes:
        - name: saq-data
          persistentVolumeClaim:
            claimName: {{ include "cong-chart.fullname" . }}-saq-data-pvc
        - name: maana-share
          persistentVolumeClaim:
            claimName: {{ include "cong-chart.fullname" . }}-maana-share-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-saq-data-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: {{ .Values.saq.persistence.size | quote }}
{{- end }}