{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.serviceAccountName" . }}
  labels:
    {{- include "cong-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-pvc-manager
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "cong-chart.fullname" . }}-pvc-manager-binding
subjects:
- kind: ServiceAccount
  name: {{ include "cong-chart.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "cong-chart.fullname" . }}-pvc-manager
  apiGroup: rbac.authorization.k8s.io
{{- end -}}