apiVersion: v1
kind: Service
metadata:
  name: cassandra1
  labels:
    app: cassandra1
spec:
  ports:
    - port: 9160
      name: thrift
    - port: 9042
      name: cql
  clusterIP: None
  selector:
    app: cassandra1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra1
spec:
  serviceName: "cassandra1"
  replicas: 1
  selector:
    matchLabels:
      app: cassandra1
  template:
    metadata:
      labels:
        app: cassandra1
    spec:
      containers:
        - name: cassandra1
          image: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/cassandra:3.11.1
          ports:
            - containerPort: 9160
            - containerPort: 9042
          env:
            - name: CASSANDRA_START_RPC
              value: "true"
            - name: CASSANDRA_BROADCAST_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
