apiVersion: v1
kind: Service
metadata:
  name: uaa-mysql1
  labels:
    app: uaa-mysql1
spec:
  ports:
    - port: 3306
  selector:
    app: uaa-mysql1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa-mysql1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uaa-mysql1
  template:
    metadata:
      labels:
        app: uaa-mysql1
    spec:
      containers:
        - name: uaa-mysql1
          image: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/mysql:5.7.21
          args:
            - "mysqld"
            - "--user=root"
            - "--verbose"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: root-password
            - name: MYSQL_DATABASE
              value: "uaa"
            - name: MYSQL_USER
              value: "uaa"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: user-password
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: "bXlzZWNyZXQ="
  user-password: "bXlzZWNyZXQ="
