apiVersion: v1
kind: Service
metadata:
  name: vault1
  labels:
    app: vault1
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault1
  labels:
    app: vault1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault1
  template:
    metadata:
      labels:
        app: vault1
    spec:
      containers:
        - name: vault1
          image: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/vault:1.0.2
          command:
            - "server"
            - "-dev"
          securityContext:
            capabilities:
              add:
                - "IPC_LOCK"
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: root-token
          ports:
            - containerPort: 8200
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
type: Opaque
data:
  root-token: "Y2hhbmdlbWU="
