# Default values for cong-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: console-app

ingress:
  enabled: false

service:
  type: ClusterIP

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

consul:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/consul
    pullPolicy: IfNotPresent
    tag: "1.19.2"
  persistence:
    size: 1Gi
  config: {}

vault:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/vault
    pullPolicy: IfNotPresent
    tag: "1.0.2"
  rootToken: "changeme"

nginx:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/nginx
    pullPolicy: IfNotPresent
    tag: "1.26.3"
  service:
    type: LoadBalancer
  configTemplate: ""
  tls:
    crt: ""
    key: ""

cassandra:
  enabled: true
  replicaCount: 1
  image:
    repository: cassandra
    pullPolicy: IfNotPresent
    tag: "4.1.3"
  persistence:
    size: 5Gi

mysql:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/mysql
    pullPolicy: IfNotPresent
    tag: "5.7.21"
  rootPassword: "mysecret"
  userPassword: "mysecret"
  persistence:
    size: 2Gi

uaa:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/cloudbreak-uaa
    pullPolicy: IfNotPresent
    tag: "1.0"
  config: {}

saq:
  enabled: true
  replicaCount: 2
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/saq
    pullPolicy: IfNotPresent
    tag: "3.0.0"
  persistence:
    size: 1Gi

kgservice:
  enabled: true
  replicaCount: 2
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/kgservice
    pullPolicy: IfNotPresent
    tag: "latest" # You need to change this

jobScheduler:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/job-scheduler
    pullPolicy: IfNotPresent
    tag: "latest" # You need to change this

jobExecutor:
  enabled: true
  replicaCount: 2
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/job-executor
    pullPolicy: IfNotPresent
    tag: "latest" # You need to change this

garbageCollector:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/garbage-collector
    pullPolicy: IfNotPresent
    tag: "3.0.0"

applicationService:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/application-service
    pullPolicy: IfNotPresent
    tag: "3.0.0"

documents:
  enabled: true
  replicaCount: 1
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/documents
    pullPolicy: IfNotPresent
    tag: "3.0.0"

bootstrap:
  enabled: true
  image:
    repository: us-docker.pkg.dev/sparkcognition-neon-dev/engineering/neon/bootstrap
    pullPolicy: IfNotPresent
    tag: "latest" # You need to change this

log4j:
  config: ""

serviceAccount:
  create: true
  name: cong-service-account
  annotations:
    iam.gke.io/gcp-service-account: terraform@avathon-saas-runtime-setup.iam.gserviceaccount.com
